apiVersion: v2
description: A Helm chart for OpenClaw (Clawdbot) - Personal AI Assistant Gateway
home: https://github.com/feiskyer/openclaw-kubernetes
keywords:
- openclaw
- clawdbot
- moltbot
- ai
- assistant
- gateway
- websocket
name: openclaw
sources:
- https://github.com/feiskyer/openclaw-kubernetes
type: application
version: 0.1.28
appVersion: 0.1.28
maintainers:
  - name: feiskyer
    url: https://github.com/feiskyer
