apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "openclaw.fullname" . }}
  labels:
    {{- include "openclaw.labels" . | nindent 4 }}
  {{- with .Values.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  serviceName: {{ include "openclaw.fullname" . }}
  selector:
    matchLabels:
      {{- include "openclaw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") $ | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "openclaw.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "openclaw.serviceAccountName" . }}
      # Auto-mount token when serviceAccount.role is set for kubectl access
      automountServiceAccountToken: {{ not (empty .Values.serviceAccount.role) }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-openclaw-data
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          command:
            - sh
            - -c
            - |
              set -e
              mkdir -p /openclaw-data
              if [ -d /home/vibe/.openclaw ] && [ -z "$(ls -A /openclaw-data 2>/dev/null)" ]; then
                cp -a /home/vibe/.openclaw/. /openclaw-data/
              fi
              if [ -f /etc/openclaw/openclaw.json ] && [ ! -f /openclaw-data/openclaw.json ]; then
                cp /etc/openclaw/openclaw.json /openclaw-data/openclaw.json
              fi
              # Seed codex config from ConfigMap (with litellm URL)
              mkdir -p /home/vibe/.codex
              if [ -f /etc/openclaw/codex-config.toml ]; then
                cp /etc/openclaw/codex-config.toml /home/vibe/.codex/config.toml
              fi
              # Seed claude settings from ConfigMap (with litellm URL)
              if [ -f /etc/openclaw/claude-settings.json ]; then
                cp /etc/openclaw/claude-settings.json /home/vibe/.claude/settings.json
              fi
          volumeMounts:
            - name: data
              mountPath: /openclaw-data
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /etc/openclaw
              readOnly: true
            - name: codex-config
              mountPath: /home/vibe/.codex
            - name: claude-config
              mountPath: /home/vibe/.claude
      {{- with .Values.initContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - openclaw
            - gateway
            - --bind
            - lan
            - --port
            - {{ .Values.openclaw.config.gateway.port | quote }}
            - --allow-unconfigured
          ports:
            - name: gateway
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: NODE_ENV
              value: "production"
            - name: OPENCLAW_STATE_DIR
              value: "/home/vibe/.openclaw"
            {{- if .Values.secrets.existingSecret }}
            # Messaging channel tokens from existing secret
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: DISCORD_BOT_TOKEN
                  optional: true
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: TELEGRAM_BOT_TOKEN
                  optional: true
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: SLACK_BOT_TOKEN
                  optional: true
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: SLACK_APP_TOKEN
                  optional: true
            # Gateway token from existing secret
            - name: OPENCLAW_GATEWAY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.existingSecret }}
                  key: OPENCLAW_GATEWAY_TOKEN
            {{- else }}
            # Messaging channel tokens from created secret
            - name: DISCORD_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "openclaw.secretName" . }}
                  key: DISCORD_BOT_TOKEN
                  optional: true
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "openclaw.secretName" . }}
                  key: TELEGRAM_BOT_TOKEN
                  optional: true
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "openclaw.secretName" . }}
                  key: SLACK_BOT_TOKEN
                  optional: true
            - name: SLACK_APP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "openclaw.secretName" . }}
                  key: SLACK_APP_TOKEN
                  optional: true
            # Gateway token from created secret
            - name: OPENCLAW_GATEWAY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "openclaw.secretName" . }}
                  key: OPENCLAW_GATEWAY_TOKEN
            {{- end }}
            # Config file path
            - name: OPENCLAW_CONFIG_PATH
              value: "/home/vibe/.openclaw/openclaw.json"
            # NPM cache directory (avoid read-only filesystem issues)
            - name: npm_config_cache
              value: "/home/vibe/.openclaw/.npm-cache"
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.extraEnvFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - openclaw
                - health
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - openclaw
                - health
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            exec:
              command:
                - openclaw
                - health
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /home/vibe/.openclaw
            - name: tmp
              mountPath: /tmp
            - name: config
              mountPath: /etc/openclaw
            - name: codex-config
              mountPath: /home/vibe/.codex
            - name: claude-config
              mountPath: /home/vibe/.claude
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.sidecars }}
            {{- toYaml . | nindent 8 }}
          {{- end }}
      volumes:
        - name: tmp
          emptyDir: {}
        - name: codex-config
          emptyDir: {}
        - name: claude-config
          emptyDir: {}
        - name: config
          configMap:
            name: {{ include "openclaw.configMapName" . }}
        {{- if .Values.persistence.existingClaim }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
        {{- else if and .Values.persistence.enabled (not .Values.persistence.useStatefulSetVolumeClaim) }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "openclaw.pvcName" . }}
        {{- else if .Values.persistence.enabled }}
        # When using StatefulSet volumeClaimTemplates, don't create extra volume
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) .Values.persistence.useStatefulSetVolumeClaim }}
  {{- if semverCompare ">=1.25-0" .Capabilities.KubeVersion.Version }}
  persistentVolumeClaimRetentionPolicy:
    {{- if eq .Values.persistence.retainPolicy "Delete" }}
    whenDeleted: Delete
    whenScaled: Delete
    {{- else }}
    whenDeleted: Retain
    whenScaled: Retain
    {{- end }}
  {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          {{- include "openclaw.labels" . | nindent 10 }}
        {{- with .Values.persistence.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        storageClassName: {{ .Values.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
  {{- end }}
